# Generated by Django 4.2 on 2025-01-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='sub_title',
            new_name='description',
        ),
    ]
