# Generated by Django 4.2 on 2025-01-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applight', '0002_rename_sub_title_banner_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About item', 'verbose_name_plural': 'About items'},
        ),
    ]
